# Generated by Django 4.1.6 on 2023-02-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appreciation_text', models.CharField(max_length=500, verbose_name='Appréciation')),
            ],
        ),
        migrations.CreateModel(
            name='Encadrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_text', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom_text', models.CharField(max_length=100, verbose_name='Prénom')),
                ('naissance_date', models.DateField(verbose_name='Date de naissance')),
                ('mail_email', models.EmailField(max_length=254, verbose_name='Adresse mail')),
                ('telephone_integer', models.PositiveIntegerField(verbose_name='Numéro de téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe_text', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('adherent_list', models.ManyToManyField(to='gestion.adherent')),
                ('encadrant_list', models.ManyToManyField(to='gestion.encadrant')),
            ],
        ),
        migrations.AddField(
            model_name='encadrant',
            name='personne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.personne'),
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire_date', models.DateTimeField(verbose_name='Date et heure')),
                ('duree_time', models.TimeField(verbose_name='Durée')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.groupe')),
            ],
        ),
        migrations.AddField(
            model_name='adherent',
            name='personne',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.personne'),
        ),
    ]
