# Generated by Django 4.1.6 on 2023-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_personne_telephone_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='telephone_integer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
