# Generated by Django 4.1.6 on 2023-02-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_personne_telephone_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='appreciation_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Appréciation'),
        ),
    ]
